services:

  mysql_service:
    image: mysql:8.0
    container_name: mysql_service
    environment:
      MYSQL_ROOT_PASSWORD: kaneki15..
      MYSQL_DATABASE: hoteles
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-net

  mongo_hoteles:
    image: mongo:7.0
    container_name: mongo_hoteles
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - backend-net

  mongo_express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo_hoteles
    networks:
      - backend-net

  user_api:
    build:
      context: ./user_api
    container_name: user_api
    restart: always
    depends_on:
      - mysql_service
    env_file:
      - ./user_api/.env
    ports:
      - "8080:8080"
    networks:
      - backend-net

  hotels_api:
    build:
      context: ./hotels_api
    container_name: hotels_api
    env_file:
      - ./hotels_api/.env
    depends_on:
      - mongo_hoteles
    ports:
      - "8082:8082"
    networks:
      - backend-net

networks:
  backend-net:

volumes:
  mongo_data:
  mysql_data:
